# -*- coding: utf-8 -*-
"""Face Detection using SCRFD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w8DW1ETWWREiYnRfFuF6dD1cKnLAIBhc
"""

# ============================================================
# Face Detection using SCRFD
# ============================================================
# Description  : Upload any image → detect all faces
#                using pretrained SCRFD model
# Model        : SCRFD via InsightFace (buffalo_l)
# Author       : Fatima
# ============================================================

# ── Step 1: Install Required Libraries ──────────────────────
!pip install insightface onnxruntime -q

# ── Step 2: Import Required Libraries ───────────────────────
import cv2                               # image processing
import numpy as np                       # numerical operations
import matplotlib.pyplot as plt          # displaying images
from insightface.app import FaceAnalysis # pretrained SCRFD model
from google.colab import files           # file upload in Colab

# ── Step 3: Load Pretrained SCRFD Model ─────────────────────
# buffalo_l = most accurate pretrained model in InsightFace
# trained on millions of faces → ready to use immediately
print("Loading SCRFD model...")
app = FaceAnalysis(name="buffalo_l")
app.prepare(ctx_id=0, det_size=(640, 640))
print("SCRFD model ready!")

# ── Step 4: Ask User to Upload Image ────────────────────────
# files.upload() opens a file picker in Google Colab
# user can upload any image from their computer
print("\nPlease upload an image...")
uploaded = files.upload()

# get uploaded filename automatically
filename = list(uploaded.keys())[0]
print(f"Image uploaded: {filename}")

# ── Step 5: Read and Prepare Image ──────────────────────────
# read uploaded image from disk
img = cv2.imread(filename)

# resize to 640x640 for better SCRFD detection
# SCRFD works best with larger images
img_resized = cv2.resize(img, (640, 640))

# ── Step 6: Run SCRFD Face Detection ────────────────────────
print("\nRunning face detection...")
faces = app.get(img_resized)
print(f"Total faces detected: {len(faces)}")

# print details for each detected face
for i, face in enumerate(faces):
    print(f"\nFace {i+1}:")
    print(f"  Bounding box : {face.bbox.astype(int)}")
    print(f"  Confidence   : {round(face.det_score, 4)}")
    print(f"  Landmarks    : {face.kps.astype(int)}")

# ── Step 7: Draw Bounding Boxes and Landmarks ───────────────
# make copy of image so original is not modified
img_result = img_resized.copy()

for i, face in enumerate(faces):
    # get bounding box coordinates as integers
    x1, y1, x2, y2 = face.bbox.astype(int)

    # draw green rectangle around detected face
    # (0, 255, 0) = green color, 2 = line thickness
    cv2.rectangle(img_result, (x1, y1), (x2, y2),
                  (0, 255, 0), 2)

    # write face number and confidence score above box
    score_text = f"Face {i+1}: {round(face.det_score, 2)}"
    cv2.putText(img_result, score_text, (x1, y1-10),
                cv2.FONT_HERSHEY_SIMPLEX, 0.5,
                (0, 255, 0), 2)

    # draw 5 facial landmarks as red dots
    # landmarks = eyes, nose, mouth corners
    for point in face.kps.astype(int):
        cv2.circle(img_result, tuple(point),
                   3, (0, 0, 255), -1)

# ── Step 8: Display Final Result ────────────────────────────
# convert BGR (OpenCV format) to RGB (matplotlib format)
img_rgb = cv2.cvtColor(img_result, cv2.COLOR_BGR2RGB)

# display image with detection results
plt.figure(figsize=(10, 8))
plt.imshow(img_rgb)
plt.title(f"Face Detection Result — {len(faces)} face(s) detected",
          fontsize=14)
plt.axis('off')
plt.show()